services:
  db:
    image: postgres:15-alpine
    container_name: makutalk_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: makupassword123
      POSTGRES_DB: makutalk_db
    ports:
      - "51213:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
